#!/usr/bin/env bash
# Transfers a file from this client to a server using SCP

# Check for correct number of parameters
if [[ $# -ne 4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 2
fi

# Copy a file using SCP
scp -i "$4" -o 'StrictHostKeyChecking no' "$1" "$3@$2":~/
