#!/usr/bin/env bash
# Install and configure HAProxy

# Instal HAProxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.6
apt-get install -y haproxy=1.6.\*

# Configure HAProxy
echo "
frontend hbnb
  bind :80
  default_backend web_servers

backend web_servers
  balance roundrobin
  server 2705-web-01 34.138.201.214:80
  server 2705-web-02 34.73.161.142
" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
