#!/usr/bin/env bash
# FizzBuzz

for (( n=1; n <= 100; n++ )); do
	if [ $((n % 15)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $((n % 5)) == 0 ]; then
		echo "Buzz"
	elif [ $((n % 3)) == 0 ]; then
		echo "Fizz"
	else
		echo $n
	fi
done
