#!/usr/bin/env bash
# Display "Holberton School" 10 times, except print "Hi" the 9th time instead.

for ((i = 1; i <= 10; i++))
do
	if [ $i == 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
done
