#!/usr/bin/env bash
# Display "Holberton School" 10 times, and also print "Hi" after the 9th time.

loop=1
while [ $loop -le 10 ]; do
	echo "Holberton School"

	if [ $loop == 9 ]; then
		echo "Hi"
	fi

	((loop++))
done
