#!/usr/bin/env bash
# Run Nginx as the "nginx" user.
chmod 644 /etc/nginx/nginx.conf
sed -i '1c\user nginx;' /etc/nginx/nginx.conf
sed -i '21c\\tlisten 8080 default_server;\n\tlisten [::]:8080 default_server;' /etc/nginx/sites-available/default
pkill apache2
sudo -H -u nginx bash -c "service nginx start"
